# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 299d1b2879153d1534ad2c87d56e40e794054a579d9a71a98221b9637ddb42417e95809b9193982ec3484b6a01ed3972b8aa716aeb58f96bb3dbf9616e8b0a29

test:
  secret_key_base: 1bf502f9e4141fb382e01632d7937a5312b6473779cce3a39ff5e62e7474670db6eaae8ebd08dfa7171834e73617cf14cdb0a1e69cd4d0f715c914390760f899

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
